"""(user-applciation):change from job offer id to job offer reference)

Revision ID: df8d50b34de7
Revises: 
Create Date: 2025-12-31 02:44:17.016543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8d50b34de7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_user_application_history_id', table_name='user_application_history')
    op.drop_index('ix_app_user_application_history_user_application_id', table_name='user_application_history')
    op.drop_table('user_application_history')
    op.drop_index('ix_app_user_applications_id', table_name='user_applications')
    op.drop_index('ix_app_user_applications_job_offer_id', table_name='user_applications')
    op.drop_index('ix_app_user_applications_user_id', table_name='user_applications')
    op.drop_table('user_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_applications',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_applications_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_offer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_offer_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_offer_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('applied_through', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'applied'::character varying"), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('application_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_applications_pkey'),
    sa.UniqueConstraint('user_id', 'job_offer_id', name='uq_user_job'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_app_user_applications_user_id', 'user_applications', ['user_id'], unique=False)
    op.create_index('ix_app_user_applications_job_offer_id', 'user_applications', ['job_offer_id'], unique=False)
    op.create_index('ix_app_user_applications_id', 'user_applications', ['id'], unique=False)
    op.create_table('user_application_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_application_id'], ['user_applications.id'], name='user_application_history_user_application_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_application_history_pkey')
    )
    op.create_index('ix_app_user_application_history_user_application_id', 'user_application_history', ['user_application_id'], unique=False)
    op.create_index('ix_app_user_application_history_id', 'user_application_history', ['id'], unique=False)
    # ### end Alembic commands ###
