"""add_certifications_column

Revision ID: 7ab0f89325a7
Revises: ab3b8c47f69f
Create Date: 2026-03-09 23:35:16.159017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ab0f89325a7'
down_revision: Union[str, None] = 'ab3b8c47f69f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_application_history_user_application_id_fkey', 'user_application_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_application_history', 'user_applications', ['user_application_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('user_profiles', sa.Column('certifications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'certifications')
    op.drop_constraint(None, 'user_application_history', schema='app', type_='foreignkey')
    op.create_foreign_key('user_application_history_user_application_id_fkey', 'user_application_history', 'user_applications', ['user_application_id'], ['id'])
    # ### end Alembic commands ###
