"""add user profile fields

Revision ID: 8a36cfb4d623
Revises: 5c79d2314356
Create Date: 2026-01-11 02:38:58.111626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a36cfb4d623'
down_revision: Union[str, None] = '5c79d2314356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_table('user_profile_education_entries')
    op.drop_table('user_profile_project_entries')
    op.drop_table('user_profile_skill_categories')
    op.drop_table('user_profile_experience_entries')
    op.drop_constraint('user_application_history_user_application_id_fkey', 'user_application_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_application_history', 'user_applications', ['user_application_id'], ['id'], source_schema='app', referent_schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_application_history', schema='app', type_='foreignkey')
    op.create_foreign_key('user_application_history_user_application_id_fkey', 'user_application_history', 'user_applications', ['user_application_id'], ['id'])
    op.create_table('user_profile_experience_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('period', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bullets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name='user_profile_experience_entries_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_profile_experience_entries_pkey')
    )
    op.create_table('user_profile_skill_categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name='user_profile_skill_categories_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_profile_skill_categories_pkey')
    )
    op.create_table('user_profile_project_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('bullets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name='user_profile_project_entries_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_profile_project_entries_pkey')
    )
    op.create_table('user_profile_education_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('school', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('coursework', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name='user_profile_education_entries_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_profile_education_entries_pkey')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('github', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('extra_curricular', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###
