"""add company_logo_url column to User_applications

Revision ID: a454f0ab6c17
Revises: e407ad6d3b51
Create Date: 2026-01-05 03:06:01.982877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a454f0ab6c17'
down_revision: Union[str, None] = 'e407ad6d3b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_application_history_user_application_id_fkey', 'user_application_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_application_history', 'user_applications', ['user_application_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('user_applications', sa.Column('company_logo_url', sa.String(), nullable=True))
    op.add_column('user_applications', sa.Column('job_offer_country', sa.String(), nullable=True))
    op.add_column('user_applications', sa.Column('job_offer_region', sa.String(), nullable=True))
    op.add_column('user_applications', sa.Column('job_offer_city', sa.String(), nullable=True))
    op.add_column('user_applications', sa.Column('resume_used_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_applications', 'resume_used_link')
    op.drop_column('user_applications', 'job_offer_city')
    op.drop_column('user_applications', 'job_offer_region')
    op.drop_column('user_applications', 'job_offer_country')
    op.drop_column('user_applications', 'company_logo_url')
    op.drop_constraint(None, 'user_application_history', schema='app', type_='foreignkey')
    op.create_foreign_key('user_application_history_user_application_id_fkey', 'user_application_history', 'user_applications', ['user_application_id'], ['id'])
    # ### end Alembic commands ###
