"""(user-applciation):change from job offer id to job offer reference)

Revision ID: e407ad6d3b51
Revises: df8d50b34de7
Create Date: 2025-12-31 02:54:17.520732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e407ad6d3b51'
down_revision: Union[str, None] = 'df8d50b34de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_application_history_user_application_id_fkey', 'user_application_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_application_history', 'user_applications', ['user_application_id'], ['id'], source_schema='app', referent_schema='app')
    op.alter_column('user_applications', 'job_offer_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_applications', 'job_offer_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'user_application_history', schema='app', type_='foreignkey')
    op.create_foreign_key('user_application_history_user_application_id_fkey', 'user_application_history', 'user_applications', ['user_application_id'], ['id'])
    # ### end Alembic commands ###
