"""add user profile table

Revision ID: f31d136cfa73
Revises: 4bf83f2daea3
Create Date: 2026-01-11 03:02:07.678594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31d136cfa73'
down_revision: Union[str, None] = '4bf83f2daea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_application_history_user_application_id_fkey', 'user_application_history', type_='foreignkey')
    op.create_foreign_key(None, 'user_application_history', 'user_applications', ['user_application_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('user_profile_project_entries', sa.Column('description', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile_project_entries', 'description')
    op.drop_constraint(None, 'user_application_history', schema='app', type_='foreignkey')
    op.create_foreign_key('user_application_history_user_application_id_fkey', 'user_application_history', 'user_applications', ['user_application_id'], ['id'])
    # ### end Alembic commands ###
